screenSize can be null.. checkit
════════ Exception caught by scheduler library ═════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The getter 'height' was called on null.
Receiver: null
Tried calling: height

When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      CoronaJump.update
package:coronajump/game.dart:53
#2      GameRenderBox._update
package:flame/game/game.dart:367
#3      GameRenderBox._tick
package:flame/game/game.dart:360
#4      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1109
...

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack
#2      SchedulerBinding.scheduleFrameCallback
package:flutter/…/scheduler/binding.dart:520
#3      GameRenderBox._scheduleTick
package:flame/game/game.dart:348
#4      GameRenderBox.attach
package:flame/game/game.dart:335
#5      RenderObjectWithChildMixin.attach
package:flutter/…/rendering/object.dart:2956
#6      AbstractNode.adoptChild
package:flutter/…/foundation/node.dart:132
...
════════════════════════════════════════════════════════════════════════════════